runtime: nodejs10
api_version: 1

env_variables:
  API_KEY: AIzaSyAS20Dpq4SpnUJYHM8h605p8VFda0VePVA



handlers:

  - url: /
    static_files: dist/vredenOnline/index.html
    upload: dist/vredenOnline/index.html
  - url: /
    static_dir: dist/vredenOnline